production:
  main:
    database: demo
    username: root
    password: 
    host: 127.0.0.1
    port: 3306
    dbargs: charset=utf8&parseTime=True&loc=Local
    pool: 5

development:
  main:
    database: demo
    username: root
    password: 
    host: 127.0.0.1
    port: 3306
    dbargs: charset=utf8&parseTime=True&loc=Local
    pool: 5
